### ISSUE TITLE
BUG : In the default example after installation the CANCELLED state is not visible in the block.

### ISSUE THREAD

**Issue by jaroet** [sawhney17/logseq-custom-workflow-plugin#5] opened 2022-04-04 11:32 UTC
I just installed your plugin and tried working with it. 

When I have a random block in my graph and I hit CMD-SHFT-ENTER a few time it starts to cycle between TODO, DONE, CANCELLED, WAITING and EMPTY. That works great. 

But when I move out of the block when the state is on CANCELLED this is not visible anymore. Also the checkmark box in front of the row is gone. It is there with all other states. When I move into the block the stated CANCELLED is there and hitting the hotkey does continue to cycle through the states. 

I guess that is not how it is supposed to work?

**Comment by sawhney17** [comment] 2022-04-04 14:01
Looks like an issue with @logseq. It treats "CANCELED" as intended but CANCELLED is unintended. I'll file an issue for now to the logseq main repo and close this. 

In short, just replace CANCELLED with CANCELED, even though it's incorrect spelling

**Comment by jaroet** [comment] 2022-04-04 15:02
Thanks for the quick response. FYI ... with CANCELED there is still no checkbox there for me. Both with 0.65 version as with today's (04-04) nightly desktop app.

**Comment by sawhney17** [comment] 2022-04-07 11:20
Yeah there isn't meant to be your checkbox. A cancel task means that the taste just has strike through because it's no longer tasks because you're sen ly canceling it. I've also submitted a fix to the main logseq repository so the next release should have that. The nightly release already does

**Closed as completed** 2022-09-30 14:57 UTC

**Comment by sawhney17** [comment] 2022-10-11 07:32
Yes. That’s the intended behaviour and you wouldn’t check off a task marked cancelled because you’re essentially marking the task as doesn’t need to be done. The text is striked  out right?
